# NLP intro

In [6]:
import numpy as np

review1 = "I LOVE this book about love"
review2 = "No this book was okay"

all_words = [text.lower().split() for text in [review1, review2]]
print(all_words)

# flatten this list, can also add lists with + operator
all_words = [word for text in all_words for word in text]
print(f"Flattened all words: {all_words}")

unique_words = set(all_words)
print(f"Unique words {unique_words}")

[['i', 'love', 'this', 'book', 'about', 'love'], ['no', 'this', 'book', 'was', 'okay']]
Flattened all words: ['i', 'love', 'this', 'book', 'about', 'love', 'no', 'this', 'book', 'was', 'okay']
Unique words {'about', 'love', 'i', 'okay', 'this', 'no', 'was', 'book'}


In [13]:
#Make dictionary of all words
vocabulary = {word: index for index, word in enumerate(unique_words)}
print(vocabulary)

def term_frequency_vectorizer(document, vocabulary):
    term_frequency = np.zeros(len(vocabulary))

    for word in document.lower().split():
        index = vocabulary[word] #This gives us the index, since the word is the key
        term_frequency[index] += 1 #Increase the term frequency for that index
    
    return term_frequency

review1_term_freq = term_frequency_vectorizer(review1, vocabulary)
review2_term_freq = term_frequency_vectorizer(review2, vocabulary)

print(review1)
print(review1_term_freq)
print(review2)
print(review2_term_freq)

{'about': 0, 'love': 1, 'i': 2, 'okay': 3, 'this': 4, 'no': 5, 'was': 6, 'book': 7}
I LOVE this book about love
[1. 2. 1. 0. 1. 0. 0. 1.]
No this book was okay
[0. 0. 0. 1. 1. 1. 1. 1.]


In [14]:
import pandas as pd

bag_of_words = pd.DataFrame([review1_term_freq, review2_term_freq], columns=vocabulary.keys(), dtype="int16")

bag_of_words

about  love  i  okay  this  no  was  book
0      1     2  1     0     1   0    0     1
1      0     0  0     1     1   1    1     1

### Feature Extraction with sklearn

In [19]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer

count_vectorizer = CountVectorizer()
bag_of_words_sparse = count_vectorizer.fit_transform([review1, review2]) # With text data we often work with sparse matrix
bag_of_words_sparse.todense(), count_vectorizer.get_feature_names_out() #It has thrown away "i"

(matrix([[1, 1, 2, 0, 0, 1, 0],
         [0, 1, 0, 1, 1, 1, 1]]),
 array(['about', 'book', 'love', 'no', 'okay', 'this', 'was'], dtype=object))

In [21]:
bag_of_words = pd.DataFrame(bag_of_words_sparse.todense(), columns=count_vectorizer.get_feature_names_out())
bag_of_words

about  book  love  no  okay  this  was
0      1     1     2   0     0     1    0
1      0     1     0   1     1     1    1

In [22]:
tfidf_transformer = TfidfTransformer()
tfidf = tfidf_transformer.fit_transform(bag_of_words_sparse) #Do not do this on really large dataset
tfidf

<2x7 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [24]:
tfidf.todense() 

matrix([[0.4078241 , 0.29017021, 0.81564821, 0.        , 0.        ,
         0.29017021, 0.        ],
        [0.        , 0.35520009, 0.        , 0.49922133, 0.49922133,
         0.35520009, 0.49922133]])

In [25]:
# Creates tfidf vector in one go 
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit_transform([review1, review2]).todense()

matrix([[0.4078241 , 0.29017021, 0.81564821, 0.        , 0.        ,
         0.29017021, 0.        ],
        [0.        , 0.35520009, 0.        , 0.49922133, 0.49922133,
         0.35520009, 0.49922133]])