### Uppgift 6

In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [7]:
df_X_train = pd.DataFrame({"x" : [0, 1, 3, 2, 2],
                        "y" : [1, 0, 2, 2, 1]})
df_y_train = [1, 1, 1, 2, 2]

test_point = pd.DataFrame({"x" : [1],
                        "y" : [1]})

In [13]:
model = KNeighborsClassifier(n_neighbors=3, metric="euclidean")
model.fit(df_X_train, df_y_train)
model.predict(test_point)

array([1])

In [12]:
model = KNeighborsClassifier(n_neighbors=5, metric="euclidean")
model.fit(df_X_train, df_y_train)
model.predict(test_point)
model.kneighbors(test_point, return_distance=True)

(array([[1.        , 1.        , 1.        , 1.41421356, 2.23606798]]),
 array([[0, 1, 4, 3, 2]]))

### Uppgift 7

In [40]:
df_X_train = pd.DataFrame({"x" : [1, 2, -2],
                        "y" : [1, 4, 2]})
df_X_train

x  y
0  1  1
1  2  4
2 -2  2

In [41]:
df_X_test = pd.DataFrame({"x" : [1, 2],
                        "y" : [2, 2]})
df_X_test

x  y
0  1  2
1  2  2

In [42]:
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(df_X_train)
X_test_scaled = scaler.transform(df_X_test)

In [43]:
X_train_scaled

array([[0.75      , 0.        ],
       [1.        , 1.        ],
       [0.        , 0.33333333]])

In [44]:
X_test_scaled

array([[0.75      , 0.33333333],
       [1.        , 0.33333333]])

In [45]:
np.sqrt((7-3)**2 + (2-6)**2)

5.656854249492381

In [46]:
np.sqrt((7-2)**2 + (3-6)**2)

5.830951894845301